### ISSUE TITLE
No JSON object could be decoded

### ISSUE THREAD

**Issue by aqzhyi** [kennedyoliveira/alfred-rates#11]
First install, work fine.

Someday, it crash.

![image](https://cloud.githubusercontent.com/assets/1500206/9976167/c80b6b68-5f0d-11e5-8ab5-e797eddaa57b.png)

I have removed it from alfred 2.7.2 (407) OS X 10.10.5, then download Rates v2.4.1 (0550eaf) to install again.

Still error.

**Comment by kennedyoliveira** [comment]
Hello @Pleasurazy, can you please run `rateclear` and after try to run `rate 849 USD TWD`, if it doesn't work, open you alfred preferences, go to workflows, then click on rates, after that click on a spider icon at top right of your screen, "toggle debug mode".

After run `rate 849 USD TWD`, `rateclear` and `rate 849 USD TWD` and post here the log output.

Thanks!

**Comment by aqzhyi** [comment]
Thanks for reply.

I did opened debug mode, then `rate 849 USD TWD`, `rateclear`, please check below:

![image](https://cloud.githubusercontent.com/assets/1500206/9979728/160783ac-5fad-11e5-93a4-d75cef5a4ba5.png)

```
Starting debug for 'Rates'

[ERROR: alfred.workflow.input.scriptfilter] Code 1: 15:33:44 workflow.py:2140 DEBUG    Workflow version : 2.4.1
15:33:44 workflow.py:1543 DEBUG    Reading settings from `/Users/pleasurazy/Library/Application Support/Alfred 2/Workflow Data/com.razor.rates/settings.json` ...
15:33:44 workflow.py:2158 ERROR    No JSON object could be decoded
Traceback (most recent call last):
  File "/Users/pleasurazy/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.70E2D3AE-9937-44F3-AC58-1EDA0E96B1A1/workflow/workflow.py", line 2148, in run
    self.check_update()
  File "/Users/pleasurazy/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.70E2D3AE-9937-44F3-AC58-1EDA0E96B1A1/workflow/workflow.py", line 2375, in check_update
    if not force and not self.settings.get('__workflow_autoupdate', True):
  File "/Users/pleasurazy/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.70E2D3AE-9937-44F3-AC58-1EDA0E96B1A1/workflow/workflow.py", line 1545, in settings
    self._default_settings)
  File "/Users/pleasurazy/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.70E2D3AE-9937-44F3-AC58-1EDA0E96B1A1/workflow/workflow.py", line 969, in __init__
    self._load()
  File "/Users/pleasurazy/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.70E2D3AE-9937-44F3-AC58-1EDA0E96B1A1/workflow/workflow.py", line 980, in _load
    for key, value in json.load(file_obj, encoding='utf-8').items():
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 351, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
15:33:44 workflow.py:2176 DEBUG    Workflow finished in 0.002 seconds.
[ERROR: alfred.workflow.input.scriptfilter] XML Parse Error 'The operation couldn’t be completed. (NSXMLParserErrorDomain error 64.)'. Row (null), Col (null): 'XML declaration allowed only at the start of the document' in XML:
<?xml version="1.0" encoding="utf-8"?>
<items><item valid="no"><title>Error in workflow 'com.razor.rates'</title><subtitle>No JSON object could be decoded</subtitle><icon>/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns</icon></item></items><?xml version="1.0" encoding="utf-8"?>
<items><item valid="no"><title>Error in workflow 'com.razor.rates'</title><subtitle>No JSON object could be decoded</subtitle><icon>/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns</icon></item></items>
[ERROR: alfred.workflow.input.scriptfilter] Code 1: 15:33:49 workflow.py:2140 DEBUG    Workflow version : 2.4.1
15:33:49 workflow.py:1543 DEBUG    Reading settings from `/Users/pleasurazy/Library/Application Support/Alfred 2/Workflow Data/com.razor.rates/settings.json` ...
15:33:49 workflow.py:2158 ERROR    No JSON object could be decoded
Traceback (most recent call last):
  File "/Users/pleasurazy/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.70E2D3AE-9937-44F3-AC58-1EDA0E96B1A1/workflow/workflow.py", line 2148, in run
    self.check_update()
  File "/Users/pleasurazy/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.70E2D3AE-9937-44F3-AC58-1EDA0E96B1A1/workflow/workflow.py", line 2375, in check_update
    if not force and not self.settings.get('__workflow_autoupdate', True):
  File "/Users/pleasurazy/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.70E2D3AE-9937-44F3-AC58-1EDA0E96B1A1/workflow/workflow.py", line 1545, in settings
    self._default_settings)
  File "/Users/pleasurazy/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.70E2D3AE-9937-44F3-AC58-1EDA0E96B1A1/workflow/workflow.py", line 969, in __init__
    self._load()
  File "/Users/pleasurazy/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.70E2D3AE-9937-44F3-AC58-1EDA0E96B1A1/workflow/workflow.py", line 980, in _load
    for key, value in json.load(file_obj, encoding='utf-8').items():
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 351, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
15:33:49 workflow.py:2176 DEBUG    Workflow finished in 0.002 seconds.
[ERROR: alfred.workflow.input.scriptfilter] XML Parse Error 'The operation couldn’t be completed. (NSXMLParserErrorDomain error 64.)'. Row (null), Col (null): 'XML declaration allowed only at the start of the document' in XML:
<?xml version="1.0" encoding="utf-8"?>
<items><item valid="no"><title>Error in workflow 'com.razor.rates'</title><subtitle>No JSON object could be decoded</subtitle><icon>/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns</icon></item></items><?xml version="1.0" encoding="utf-8"?>
<items><item valid="no"><title>Error in workflow 'com.razor.rates'</title><subtitle>No JSON object could be decoded</subtitle><icon>/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns</icon></item></items>
```

**Comment by kennedyoliveira** [comment]
Hello @Pleasurazy! Thx for your feedback, could you please try to delete the folder `/Users/pleasurazy/Library/Application Support/Alfred 2/Workflow Data/com.razor.rates` and run the command again?

**Comment by aqzhyi** [comment]
It WORKS!!

**Comment by kennedyoliveira** [comment]
@Pleasurazy i'm glad to help!

**Comment by aqzhyi** [comment]
Thank you very much.

**Comment by kennedyoliveira** [comment]
@Pleasurazy your welcome! And closing the issue, if you find any bugs or have any suggestion, feels free to open more!
